### PR TITLE
CM-359: Remove konflux specific configs

### PR DESCRIPTION
**Pull request by bharath-b-rh**
Remove Dockerfiles created specifically for konflux, since its now hosted in https://github.com/openshift/cert-manager-operator-release.

### CODE REVIEW

**Comment by swghosh** [comment]
/lgtm
/label docs-approved
/label px-approved
No user facing chanages, this is only a redundancy de-dup effort as same files landed into [o/cert-manager-operator-release repo](https://github.com/openshift/cert-manager-operator-release) recently.

**Comment by swghosh** [comment]
/cc @lunarwhite
for qe-approved label

**Review by lunarwhite — COMMENTED** [review]
/label qe-approved

**Pull request merged**
