### PR TITLE
Updates the reviewers and approvers

### PR DESCRIPTION
**Pull request by TrilokGeer**
Updates the reviewers and approvers list based on recent contributors and in-active members.

### CODE REVIEW

**Comment by xingxingxia** [comment]
@lunarwhite , would you like to be listed as reviewer? I see you actively reviewed some PRs in this repo.

**Comment by lunarwhite** [comment]
@xingxingxia Thanks for nominating me. I'd be fully honored to serve as a reviewer. 

@TrilokGeer @swghosh ^^ May I ask for your approval if this request is acceptable?

**Comment by swghosh** [comment]
@lunarwhite can you add qe-approved label to this PR?
On a follow-up PR, I can add you as reviewer.

**Comment by lunarwhite** [comment]
Definitely
/label qe-approved

**Pull request merged**
