### PR TITLE
Fix z-stream release channel to stable-v1.11

### PR DESCRIPTION
**Pull request by thejasn**
CPaaS has a gated check where operator cannot
be released on a channel that already has a higher 
version as its head. This is a follow up for v1.11.5 (Rapid reset CVE fix).

### CODE REVIEW

**Comment by thejasn** [comment]
Wait for https://github.com/openshift/release/pull/44697

**Comment by thejasn** [comment]
/cc @lunarwhite @xingxingxia
for qe-approved label

**Comment by thejasn** [comment]
/cc @davemulford 
for px-approved label

**Review by lunarwhite — COMMENTED** [review]
/label qe-approved

**Comment by xingxingxia** [comment]
@thejasn @lunarwhite , understood the gate check issue, but not sure whether this fix will make new v1.11.x not shown in stable-v1 any more? Before, it shows.

**Comment by xingxingxia** [comment]
Tried to pre-merge examine my above question with cluster-bot, CC @lunarwhite about this method:
```
catalog build openshift/cert-manager-operator#158 cert-manager-operator-bundle
```
Then used the catalog `registry.build05.xx.xxxxxxxxx.org/ci-ln-xxxxxxx/pipeline:catalog` from it. Got channel `ci-chat-bot` only as below screenshot, no stable-v1.11 channel, I think this is a config problem @thejasn @swghosh WDTY?
Screenshot from 2023-10-26 12-23-59

$ oc get packagemanifest -n openshift-marketplace -o yaml -l catalog=cm-pre-merge-158
```
        version: 1.11.5
      entries:
      - name: cert-manager-operator.v1.11.5
        version: 1.11.5
      name: ci-chat-bot
    defaultChannel: ci-chat-bot
    packageName: cert-manager-operator
```

**Comment by thejasn** [comment]
> Tried to pre-merge examine my above question with cluster-bot, CC @lunarwhite about this method:
> 
> ```
> catalog build openshift/cert-manager-operator#158 cert-manager-operator-bundle
> ```
> 
> Then used the catalog `registry.build05.xx.xxxxxxxxx.org/ci-ln-xxxxxxx/pipeline:catalog` from it. Got channel `ci-chat-bot` only as below screenshot, no stable-v1.11 channel, I think this is a config problem @thejasn @swghosh WDTY? Screenshot from 2023-10-26 12-23-59
> 
> $ oc get packagemanifest -n openshift-marketplace -o yaml -l catalog=cm-pre-merge-158
> 
> ```
>         version: 1.11.5
>       entries:
>       - name: cert-manager-operator.v1.11.5
>         version: 1.11.5
>       name: ci-chat-bot
>     defaultChannel: ci-chat-bot
>     packageName: cert-manager-operator
> ```

The channel name is from cluster-bot. It does not read the channel name from the ci job config or the CSV, instead has a hard-coded default value. ([ref](https://github.com/openshift/ci-chat-bot/blob/f226b7a71a8fe14781684f2011dbcb31d3a78711/pkg/catalog/catalog.go#L249))

**Comment by thejasn** [comment]
> @thejasn @lunarwhite , understood the gate check issue, but not sure whether this fix will make new v1.11.x not shown in stable-v1 any more? Before, it shows.

Yes, post this fix v1.11.5 will not show up on `stable-v1` and any new `v1.11.z+1` also will not show up on the `stable-v1` channel anymore. This release's upgrade graph can be tested using `opm alpha render-graph -p cert-manager-operator <opm-index-image-build-on-top-of-4.13-catalog-index>`.

**Comment by swghosh** [comment]
/remove-hold
as https://github.com/openshift/release/pull/44697 is merged

**Comment by swghosh** [comment]
/retitle [cert-manager-1.11] Fix z-stream release channel to stable-v1.11

**Pull request merged**
