### PR TITLE
CM-183: Add infrastructure feature annotations

### PR DESCRIPTION
**Pull request by swghosh**
Added Infrastructure features for OpenShift catalog metadata as per [CFC best practices](https://docs.engineering.redhat.com/display/CFC/Best_Practices).

PS: OCPBUGS-8665 reference for addition of `token-auth-azure`. While `token-auth-aws` and `token-auth-gcp` was implemented previously in https://github.com/openshift/cert-manager-operator/pull/120 and `proxy-aware` in https://github.com/openshift/cert-manager-operator/pull/103.

### CODE REVIEW

**Comment by xingxingxia** [comment]
I read the `features.operators.openshift.io/cnf|cni|csi` "annotations can be omitted". So adding:
/qe-approved
Backport to older branches if needed.
FYI @lunarwhite

**Comment by swghosh** [comment]
I think @xingxingxia you wanted to mean
/label qe-approved

**Comment by swghosh** [comment]
/label docs-approved
(no doc req for this change immediately)

**Comment by swghosh** [comment]
/cc @davemulford 
for px-approved label

**Comment by swghosh** [comment]
/assign @TrilokGeer 
JFYI, the CVP tests impose a warning right now without these feature annotations but in near future the absence of these annotations would result in gated test error in our release.

**Comment by xingxingxia** [comment]
```
/uncc @deads2k
```

Do we need BTW update obsolete https://github.com/openshift/cert-manager-operator/blob/master/OWNERS in separate PR?

**Comment by swghosh** [comment]
> Do we need BTW update obsolete https://github.com/openshift/cert-manager-operator/blob/master/OWNERS in separate PR?

Yes, need to do that; to update that file.

**Pull request merged**
