### PR TITLE
CM-215: add nodeaffinity for non-x86 archs

### PR DESCRIPTION
**Pull request by chiragkyal**
add nodeaffinity for non-x86 archs

 - arm64
  - ppc64le
  - s390x

https://issues.redhat.com/browse/CM-215

### CODE REVIEW

**Comment by swghosh** [comment]
/label docs-approved
this specific PR shouldn't require docs, and we already have doc labels in place for 1.13 release (this PR is expected to merge only after 1.13 bump in master)

**Comment by swghosh** [comment]
/cc @lunarwhite @xingxingxia 
for qe-approved label
ref: https://github.com/openshift/cert-manager-operator/pull/146#issuecomment-1754325219

**Review by lunarwhite — COMMENTED** [review]
/label qe-approved

**Pull request merged**
