### PR TITLE
OCPBUGS-11647: Use installMode AllNamespaces in csv

### PR DESCRIPTION
**Pull request by swghosh**
Ref doc for installModes: https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata

Signed-off-by: Swarup Ghosh <swghosh@redhat.com>

### CODE REVIEW

**Comment by swghosh** [comment]
@xingxingxia can you please add qe-approved label to this one also, this fix should then be available in the following rc for you to test it out next time.

**Comment by dboc** [comment]
Hello,

I do not know if the right place to ask, but the new version "cert-manager Operator for Red Hat OpenShift 1.12.0" coming with this feature : https://github.com/openshift/cert-manager-operator/pull/121#top (installMode AllNamespace)?

**Pull request closed without merging**
