### PR TITLE
Few doc changes

### PR DESCRIPTION
**Pull request by swghosh**
Signed-off-by: Swarup Ghosh <swghosh@redhat.com>

### CODE REVIEW

**Comment by thejasn** [comment]
/override test e2e-operator
since doesn't affect code changes 
/lgtm

**Comment by thejasn** [comment]
/override pull-ci-openshift-cert-manager-operator-cert-manager-1.11-e2e-operator
since doesn't affect code changes

**Comment by swghosh** [comment]
/hold
for https://github.com/openshift/release/pull/41178 to merge first

**Comment by swghosh** [comment]
the more extensive product docs for ambient credentials have already made it to https://github.com/openshift/openshift-docs, so this is just a dev doc change
/label docs-approved

**Pull request merged**
