### PR TITLE
CM-182: Update cert-manager 1.12.4

### PR DESCRIPTION
**Pull request by thejasn**
- Updated manifest
- Updated deps
- Updated misc references

### CODE REVIEW

**Comment by thejasn** [comment]
Waiting for https://github.com/openshift/release/pull/43286

**Comment by thejasn** [comment]
/cc @davemulford
for px-approved label
/cc @xingxingxia 
for qe-approved label
/cc @xenolinux
for docs-approved label

**Comment by thejasn** [comment]
e2e failures due to 
```
level=fatal msg=failed to fetch Terraform Variables: failed to fetch dependency of "Terraform Variables": failed to generate asset "Platform Provisioning Check": baseDomain: Invalid value: "origin-ci-int-aws.dev.rhcloud.com": the zone already has record sets for the domain of the cluster: [api.ci-op-8g8vzdn6-9002d.origin-ci-int-aws.dev.rhcloud.com. (A), \052.apps.ci-op-8g8vzdn6-9002d.origin-ci-int-aws.dev.rhcloud.com. (A)]
```

Should get cleared up in some time. (https://docs.ci.openshift.org/docs/internals/#namespace-initialization)

**Comment by swghosh** [comment]
https://github.com/openshift/release/pull/43445 -- updates operand image tags to use v1.12.4 in CI jobs.

**Review by lunarwhite — COMMENTED** [review]
/label qe-approved will do post merge test

**Pull request merged**
