### PR TITLE
CM-62: Rebase cert-manager v1.11.1

### PR DESCRIPTION
**Pull request by swghosh**
[[v1.11.1](https://github.com/cert-manager/cert-manager/releases/tag/v1.11.1)] Rebase Checklist:

- [x] go dependencies

```
go get github.com/cert-manager/cert-manager@v1.11.1
go mod tidy
go mod vendor
```
- [x] openshift/release CI update related PRs
    - [x] operand image mirroring with new tag https://github.com/openshift/release/pull/38801
    - [x] ci pipeline use updated operand image tags https://github.com/openshift/release/pull/38800

Signed-off-by: Swarup Ghosh <swghosh@redhat.com>

### v1.11.1

> In v1.11.1, we updated the base images used for cert-manager containers. In addition, the users of the Venafi issuer will see less certificates repeatedly failing.
> 
> If you are a user of Venafi TPP and have been having issues with the error message This certificate cannot be processed while it is in an error state. Fix any errors, and then click Retry, please use this version.
> 
> **Bug/regression**: https://github.com/cert-manager/cert-manager/pull/5815, https://github.com/cert-manager/cert-manager/pull/5930, https://github.com/cert-manager/cert-manager/pull/5674, https://github.com/cert-manager/cert-manager/pull/5819, https://github.com/cert-manager/cert-manager/pull/5726
> 
> **Other**: https://github.com/cert-manager/cert-manager/pull/5730

### CODE REVIEW

**Comment by swghosh** [comment]
/cc @thejasn 
this should be up for merge after https://github.com/openshift/release/pull/38800

**Comment by xingxingxia** [comment]
Can't pre-merge test today. Adding label to unblock merge.
/label qe-approved
BTW FYI will be in local holiday till May 03.

**Comment by swghosh** [comment]
/label docs-approved
adding the label for now, as docs for 1.11.1 is superseded by 1.11.0 (https://github.com/openshift/cert-manager-operator/pull/113#issuecomment-1517725513)
cc: @xenolinux

**Pull request merged**
